### ISSUE TITLE
ls: Compatibility Tracking Issue

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#1872]
I've made an overview of all options that need to be added and defaults that need to be changed in `ls` to reach full compatibility with GNU `ls`. I hope this might help people out who want to contribute, without adding to many issues to the issue list.

The items marked with :one: are the ones I think make Good First Issues.

- [x] Formats
  - [x] `-x` & `--format=across` & `--format=horizontal`
  - [x] `-m` & `--format=commas`
  - [x] Make `-n` overrideable (similar to `-o` and `-g`)
- [ ] Date & time
  - [x] `--time=birth` & `--time=creation`
  - [x] `--time-style=full-iso`
  - [x] `--time-style=long-iso`
  - [x] `--time-style=iso`
  - [ ] `--time-style=locale` (works, but not locale-specific yet)
  - [ ] `--time-style=+FORMAT` like in `date`
  - [ ] `posix-` prefix for `--time-style`
  - [x] `--full-time`
  - [x] Default: follow environment variable `TIME_STYLE` or `locale`
- [ ] Escaping and quoting
  - [x] `-b`. `--escape`& `--quoting-style=escape`
  - [x] `-Q`, `--quote-name` & `--quoting-style=c`
  - [x] `-N`, `--literal` & `--quoting-style=literal`
  - [x] `--quoting-style=shell` & `--quoting-style=shell-always`
  - [x] `--quoting-style=shell-escape` & `--quoting-style=shell-escape-always`
  - [ ] `--quoting-style=locale`
  - [ ] `--quoting-style=clocale`
  - [ ] Default: follow environment variable `QUOTING_STYLE` or `shell-escape`.
  - [ ] Space in front of file names without quotes if there are names with quotes. 
- [ ] Control characters
  - [x] `-q` & `--hide-control-characters`
  - [x] `--show-control-characters`
  - [ ] Set default to `-q` if the output is a terminal.
- [ ] Sorting
  - [x] `-U` & `--sort=none`
  - [x] `-v` & `--sort=version` (also used in `sort`, so might make sense to put this in `uucore`)
  - [x] `-X` & `--sort=extension`
  - [ ] Make sorting by name locale-specific (currently only C-locale is implemented)
  - [ ] :one: `--group-directories-first`
  - [ ] `-f` (enable `-aU`, disable `-ls --color`)
- [x] Dereferencing
  - [x] `-H` & `--dereference-command-line`
  - [x] `--dereference-command-line-symlink-to-dir`
- [x] Hiding
  - [x] `--hide`
  - [x] `-I` & `--ignore`
- [x] Indicator style
  - [x] `--indicator-style` with options: `none`, `slash`, `file-type`, `classify`
  - [x] `-p` (equivalent to `--indicator-style=slash`)
  - [x] `--file-type` (equivalent to `--indicator-style=file-type`)
- [ ] Block size (these should mainly be implemented in `uucore`, since they are used by multiple programs)
  - [ ] `-s` & `--size`
  - [ ] `-k` & `--kibibytes` (equivalent to `--block-size=1K`)
  - [ ] `--block-size`
  - [ ] Default: Determine block size from environment variables.
- [ ] Loose ends: The options that didn't fit into the categories above
  - [x] `-w` & `--width`
  - [ ] `-T` & `--tabsize`
  - [ ] `-Z` & `--context`
  - [ ] `-D` & `--dired`
  - [ ] `--hyperlink`
  - [ ] Show total size of directories in the long format

**Comment by sylvestre** [comment]
Bravo for this work!

Don't hesitate to create new issues as "good first bugs"!

**Comment by LevitatingBusinessMan** [comment]
@tertsdiepraam That's another few points to tick off

**Comment by tertsdiepraam** [comment]
@LevitatingBusinessMan Thanks for reminding me!

**Comment by LevitatingBusinessMan** [comment]
@tertsdiepraam Don't forget the `posix` time-styles. And the `TIME_STYLE` environemntal variable works already.

**Comment by siebenHeaven** [comment]
Nice list :) - I was implementing 'total size' related feature which I noticed to be missing from output.
I think it aligns with the last item in the list?

**Comment by tertsdiepraam** [comment]
Yes, that's what that was supposed to be! I rewrote it a bit to make it clearer (hopefully). Looking forward to the PR!

**Comment by siebenHeaven** [comment]
Thanks for confirming - it was already clear as is, I just was double confirming.

**Comment by LevitatingBusinessMan** [comment]
@sylvestre did you close this by mistake?

**Comment by sylvestre** [comment]
nah, it was closed when the PR has been merged!

**Comment by tertsdiepraam** [comment]
Indeed! We're currently also using the `is_terminal` crate in other utils, which has the same interface, I think. So this should be pretty easy to do.

**Comment by LevitatingBusinessMan** [comment]
https://github.com/uutils/coreutils/blob/main/src/uu/ls/src/ls.rs#L830-L837

Judging by this code, this is already done. Though I am not sure if it is correctly tested.

**Comment by radhesh1** [comment]
was this one completed?

**Comment by sylvestre** [comment]
nope, we still have some options not passing compared to GNU

**Comment by naoNao89** [comment]
The `-T` and `--tabsize` options for the `ls` command have already been fully implemented. #7616

**Comment by naoNao89** [comment]
#### Date & time
- [x] `--time-style=+FORMAT` like in `date` — **PR #7616** • Code: `src/uu/ls/src/ls.rs:301-314`
- [x] `posix-` prefix for `--time-style` — **Commit a1519e1b7** • Code: `src/uu/ls/src/ls.rs:277-290` • Tests: `tests/by-util/test_ls.rs:2028-2069`

#### Block size
- [x] `-s` & `--size` — **Implemented** • Code: `src/uu/ls/src/ls.rs:1642-1647`
- [x] `-k` & `--kibibytes` — **Implemented** • Code: `src/uu/ls/src/ls.rs:1592-1597`

#### Loose ends
- [x] `-T` & `--tabsize` — **PR #7616** (538355fb6) • Code: `src/uu/ls/src/ls.rs:1200-1206` • Tests passing
- [x] `-Z` & `--context` — **PR #4476** • Code: `src/uu/ls/src/ls.rs:1745-1750`
- [x] `-D` & `--dired` — **PRs #5299, #5305, #5341, #6144, #6538** • Module: `src/uu/ls/src/dired.rs` • 10+ tests

**Comment by keys-i** [comment]
could I help out as well?

**Comment by LevitatingBusinessMan** [comment]
@keys-i Definitely, I just realized the locales here don't work yet. It's one of the last remaining issues. You could look at how locales are done in `date` and apply the same here. 

There's even a closed PR for it which you could rebase.

**Comment by sylvestre** [comment]
WIP: 
https://github.com/uutils/coreutils/pull/11669

**Comment by ed9w2in6** [comment]
I wish to mention that https://github.com/uutils/coreutils/issues/6697 is a compatibility issue with GNU `ls` on
`--dired`  / `-D` that is yet to be fixed.
There is a pull (https://github.com/uutils/coreutils/pull/6699) but some unknown issue seems to be blocking it from merging.

**Comment by vladanan** [comment]
On Ubuntu server 26.04 with uutils 0.8.0 sort is not working with `--group-directories-first` even with added `--sort=name`. I had to transplant `ls` from coreutils and get the output I need for serveral aliases.

**Comment by reini-1** [comment]
Same issue here
