### ISSUE TITLE
join: failing GNU tests

### ISSUE THREAD

**Issue by jtracey** [uutils/coreutils#2634]
Since it seems like it could be useful to have this information somewhere, here are the remaining failing GNU tests for join:

- [x] 3c: no support for joins with a null field separator, `-t "\0"` (#2881)
- [x] 10b: broken comparisons with empty fields (#2908)
- [x] sp-vs-blank: `\f` (form feed) seems to be interpreted as a newline (#2851)
- [x] 8-bit-t: 8-bit characters aren't valid unicode, cause a panic (first half:  #2851, second half: #2902)
- [x] bigfield1 and bigfield2: very large integers cause parsing as a field number to fail ( #2882)
- [x] invalid-j: test expects the invalid `-j` error to trigger before the missing args error ([patched upstream](https://github.com/coreutils/coreutils/commit/1d5dbb82030a2ca7aef606d36a9d04863240c7a8), #2919)
- [x] chkodr-4 and chkodr-7: GNU has relaxed order checks by default; see `info join -n "General options in join"` (#2908)
- [x] chkodr-5, chkodr-5b, chkodr-5c, and header3: slight differences in "not sorted" error message (#2899)
- [x] chkodr-5d and chkodr-5e: missing additional error messages (#2908)
- [x] z1, z4, z5, z6: `-z` flag (null-terminated lines) isn't supported (#2880)

**Comment by jtracey** [comment]
Once all the open PRs are merged, all the GNU tests for join [are passing](https://github.com/jtracey/coreutils/runs/4909700232?check_suite_focus=true#step:14:20) (note that the CI won't reflect this until the [workflows are updated](https://github.com/uutils/coreutils/blob/8a787fe0287636c601f57e2ef1ce8136cf1cd1c0/.github/workflows/GnuTests.yml#L21) to use the [fixed invalid-j test](https://github.com/coreutils/coreutils/commit/1d5dbb82030a2ca7aef606d36a9d04863240c7a8)).

**Comment by tertsdiepraam** [comment]
Excellent! Could you open a PR to update the workflow?
