### ISSUE TITLE
Get remaining GNU test cases from ERROR to at least FAIL

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3320]
From https://github.com/uutils/coreutils-tracking/blob/main/gnu-full-result.json, here are the remaining GNU test cases that are marked as ERROR (as opposed to FAIL, PASS, or SKIP):

- [x] tests/cp/cp-parents.sh - see #3332, #3894, #4071
- [x] tests/cp/preserve-slink-time.sh - see #3364, #3531
- [x] tests/cp/sparse-extents.sh - see #3362 
- [x] tests/cp/sparse.sh - see #3362
- [x] tests/dd/no-allocate.sh - see #3321 
- [x] tests/ls/nameless-uid.sh - see #3380
- [ ] tests/misc/csplit-io-err.sh - see #2925 
- [x] tests/misc/shuf.sh - see #3329
- [x] tests/misc/usage_vs_getopt.sh
- [x] tests/split/filter.sh - see #3281
- [ ] tests/tail-2/inotify-rotate-resources.sh - implemented in pull request #2695 but errors due to https://github.com/uutils/coreutils/blob/702a0b7a34b60a81e3fc1cf5423e9902e5cb3c13/src/uu/tail/README.md?plain=1#L35-L38

It would nice to get them from ERROR to at least FAIL.

**Comment by sylvestre** [comment]
Great idea! thanks

**Comment by jfinkels** [comment]
I updated the `tests/tail-2/inotify-rotate-resources.sh` item with comments from a recent pull request that implemented the missing behavior.

**Comment by jfinkels** [comment]
I marked some more items as completed. There are now five remaining tests in the ERROR state.

**Comment by jfinkels** [comment]
`tests/cp/cp-parents.sh` is now no longer in the ERROR state due to #4071.

**Comment by jfinkels** [comment]
and `tests/split/filter.sh` is also no longer in the ERROR state due to #3281

**Comment by jfinkels** [comment]
`tests/dd/no-allocate.sh` is no longer ERROR (now in FAIL state) due to #4164

**Comment by tertsdiepraam** [comment]
Wow we're getting close on this one! Nice work!

**Comment by cakebaker** [comment]
Closing this ticket as the two remaining test cases in the list above are no longer marked `ERROR`: `csplit-io-err.sh` is `SKIP` and `inotify-rotate-resources.sh` is `FAIL`.

**Comment by jfinkels** [comment]
Fantastic! Thanks all
