### ISSUE TITLE
[Meta bug] GNU testsuite

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3336]
The goal of this meta bug is to reference all GNU tests failing and what we need to fix them.

- [ ] https://github.com/uutils/coreutils/issues/3320
- [ ] https://github.com/uutils/coreutils/issues/3332
- [x] https://github.com/uutils/coreutils/issues/3331
- [x] https://github.com/uutils/coreutils/issues/3333
- [x] https://github.com/uutils/coreutils/issues/3171
- [x] https://github.com/uutils/coreutils/issues/3163
- [ ] https://github.com/uutils/coreutils/issues/3147
- [ ] https://github.com/uutils/coreutils/issues/2930
- [x] https://github.com/uutils/coreutils/issues/3337
- [x] https://github.com/uutils/coreutils/issues/3519

**Comment by sylvestre** [comment]
We moved to project mgmt for this:
https://github.com/orgs/uutils/projects/1
